title: Javier Santos
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Msc graduate looking for my first Data Science job, in this page you will find my Master Thesis: "Identifying the key success factors for NFT projects using Machine Learning"
  <br><br>
  In this paper I create a database, create and manipulate variables, select the most informative ones using stepwise regression and all possible regression, build three 
  predictive models: linear reression, bayesian regression and decision tree, and discuss and evaluate the performance of each model. The goal of this paper is to
  help investors and operators in Web 3 make more informed decisions.
  <br><br>
  <a href="https://www.linkedin.com/in/javsantosp/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal

